-- MySQL Script generated by MySQL Workbench
-- Ter 20 Nov 2018 18:05:40 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema laboratorio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laboratorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laboratorio` DEFAULT CHARACTER SET utf8 ;
USE `laboratorio` ;

-- -----------------------------------------------------
-- Table `laboratorio`.`logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`logins` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`cursos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cod_UNIQUE` (`cod` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`alunos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(12) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `id_curso` INT UNSIGNED NOT NULL,
  `id_login` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  INDEX `fk_alunos_logins1_idx` (`id_login` ASC),
  INDEX `fk_alunos_cursos2_idx` (`id_curso` ASC),
  CONSTRAINT `fk_alunos_logins1`
    FOREIGN KEY (`id_login`)
    REFERENCES `laboratorio`.`logins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_cursos2`
    FOREIGN KEY (`id_curso`)
    REFERENCES `laboratorio`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`centros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`centros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(6) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`laboratorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`laboratorios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `id_centro` INT UNSIGNED NOT NULL,
  `computadores` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_laboratorios_centros1_idx` (`id_centro` ASC),
  CONSTRAINT `fk_laboratorios_centros1`
    FOREIGN KEY (`id_centro`)
    REFERENCES `laboratorio`.`centros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`professores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(12) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `id_centro` INT UNSIGNED NOT NULL,
  `id_login` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  INDEX `fk_professores_centros1_idx` (`id_centro` ASC),
  INDEX `fk_professores_logins1_idx` (`id_login` ASC),
  CONSTRAINT `fk_professores_centros1`
    FOREIGN KEY (`id_centro`)
    REFERENCES `laboratorio`.`centros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professores_logins1`
    FOREIGN KEY (`id_login`)
    REFERENCES `laboratorio`.`logins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`datas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`datas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_reserva` DATE NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_termino` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`reservas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_professor` INT UNSIGNED NOT NULL,
  `id_laboratorio` INT UNSIGNED NOT NULL,
  `id_data` INT UNSIGNED NOT NULL,
  `status` VARCHAR(100) NULL,
  `obs` TEXT(300) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservas_laboratorios1_idx` (`id_laboratorio` ASC),
  INDEX `fk_reservas_professores1_idx` (`id_professor` ASC),
  INDEX `fk_reservas_datas1_idx` (`id_data` ASC),
  CONSTRAINT `fk_reservas_laboratorios1`
    FOREIGN KEY (`id_laboratorio`)
    REFERENCES `laboratorio`.`laboratorios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_professores1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `laboratorio`.`professores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_datas1`
    FOREIGN KEY (`id_data`)
    REFERENCES `laboratorio`.`datas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
